type: default-flatpaks
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub
  repo-title: "Flathub (system)"
  install:
    - org.freedesktop.Platform.ffmpeg-full//22.08
    - com.raggesilver.BlackBox
    - org.gnome.Calculator
    - org.gnome.Calendar
    - org.gnome.Characters
    - org.gnome.Connections
    - org.gnome.Contacts
    - org.gnome.Evince
    - org.gnome.Loupe
    - org.gnome.Logs
    - org.gnome.Maps
    - org.gnome.NautilusPreviewer
    - org.gnome.TextEditor
    - org.gnome.Weather
    - org.gnome.baobab
    - org.gnome.clocks
    - org.gnome.font-viewer
    - com.mattjakeman.ExtensionManager
    - com.github.tchx84.Flatseal
    - org.fedoraproject.MediaWriter
    - io.missioncenter.MissionCenter
    - org.gnome.World.PikaBackup
  remove:
    - org.gnome.Cheese
    - org.gnome.eog