type: fonts
fonts:
  nerd-fonts:
    - CascadiaCode
    - FiraCode
    - Hack
    - JetBrainsMono
    - NerdFontsSymbolsOnly
  google-fonts:
    - Noto Color Emoji
    - Noto Sans
    - Noto Sans Math
    - Noto Serif
    - Open Sans
    - Roboto