type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo

install:
  # GNOME Extensions
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-just-perfection
  - gnome-shell-extension-tailscale-status
  - nautilus-python
remove:
  - gnome-software-rpm-ostree
  - gnome-tour