type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/ublue-os/distrobox-git/repo/fedora-%OS_VERSION%/ublue-os-distrobox-git-fedora-%OS_VERSION%.repo
  # - https://copr.fedorainfracloud.org/coprs/stevenlin/emacs-pgtk-nativecomp/repo/fedora-%OS_VERSION%/stevenlin-emacs-pgtk-nativecomp-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
install:
  # GNOME Extensions
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-just-perfection
  - gnome-shell-extension-tailscale-status
  # GTK-Theme
  - gnome-themes-extra
  # Repo Font
  - liberation-fonts
  # Podman
  - podman-plugins
  - podman-tui
  # Utils
  - bat
  - dbus-x11
  - distrobox-git
  - fd-find
  - gh
  - git-credential-libsecret
  - glab
  - iotop
  - libxcrypt-compat
  - mesa-libGLU
  - nautilus-python
  - pulseaudio-utils
  - p7zip
  - p7zip-plugins
  - ripgrep
  - tmux
  - util-linux-user
  - wezterm
  - wireguard-tools
  - wl-clipboard
  # Samba
  - samba-dcerpc
  - samba-ldb-ldap-modules
  - samba-winbind-clients
  - samba-winbind-modules
  - samba
  # Pano
  - libgda-sqlite
  - libgda
  # Starship
  - starship
  # Firefox Extensions
  - mozilla-ublock-origin
  - mozilla-privacy-badger
  # Chromium
  - chromium
  - fedora-chromium-config
  - fedora-chromium-config-gnome
  - fedora-chromium-config-gssapi
  # VSCode
  - code
  # Tailscale
  - tailscale
  # Docker
  - containerd.io
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  # Google-Chrome
  - google-chrome-stable
  # # Emacs - Use Script for swap to 29.1
  # - emacs
  # - libtool
  # - cmake
  # Installed using a script
  # Google-Chrome
  # Pano Gnome Extension

remove:
  - distrobox
  - gnome-software-rpm-ostree
  - gnome-tour

optfix:
  - google