type: script
scripts:
  # this sets up the proper policy & signing files for signed images to work
  - signing.sh
  # - alternatives-workarounds.sh
  - emacs.sh
  - devpod.sh
  # - google-chrome.sh
  - post-install-sway.sh