type: script
scripts:
  # this sets up the proper policy & signing files for signed images to work
  - signing.sh
  - alternatives-workarounds.sh
  - devpod.sh
  - google-chrome.sh
  - pano.sh
  - post-install.sh