type: script
scripts:
  - alternatives-workarounds.sh
  - docker-compose.sh
  - pano.sh
  # - image-info.sh
  - post-install.sh
  # this sets up the proper policy & signing files for signed images to work
  - signing.sh