modules:
  - from-file: module_config/files.yml
  - from-file: module_config/early-script.yml
  - from-file: module_config/packages.yml
  - from-file: module_config/bling.yml
  - from-file: module_config/fonts.yml
  - from-file: module_config/systemd.yml
  - from-file: module_config/flatpak.yml
  - from-file: module_config/yafti.yml