# image will be published to ghcr.io/<user>/<name>
name: m2-ublue
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README
      - usr/etc/yum.repos.d: /etc/yum.repos.d
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # GNOME Extensions
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-just-perfection
      # GTK-Theme
      - gnome-themes-extra
      # Podman
      - podman-plugins
      - podman-tui
      # Utils
      - dbus-x11
      - git-credential-libsecret
      - iotop
      - libxcrypt-compat
      - mesa-libGLU
      - pulseaudio-utils
      - p7zip
      - p7zip-plugins
      - tmux
      - wireguard-tools
      - wl-clipboard
      # Samba
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - samba
      # Pano
      - libgda-sqlite
      - libgda
      # Starship
      - starship
      # Firefox Extensions
      - mozilla-ublock-origin
      - mozilla-privacy-badger
      # VSCode
      - code
      # Tailscale
      - tailscale
      # Chrome
      # - google-chrome-stable
    remove:
      - gnome-software-rpm-ostree
      - gnome-tour

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      # - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
      - devpod # https://devpod.sh/ as an rpm
  
  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaCode
        - FiraCode
        - Hack
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - ublue-system-setup.service
        - ublue-update.timer
        - tailscaled.service
    user:
      enabled:
        - podman.socket

  - type: default-flatpaks
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system)"
      install:
        - org.freedesktop.Platform.ffmpeg-full//22.08
        - com.raggesilver.BlackBox
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Evince
        - org.gnome.Loupe
        - org.gnome.Logs
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.font-viewer
        - com.mattjakeman.ExtensionManager
        - com.github.tchx84.Flatseal
        - org.fedoraproject.MediaWriter
        - io.missioncenter.MissionCenter
        - com.sindresorhus.Caprine
        - com.discordapp.Discord
        - org.gnome.World.PikaBackuprita
        - com.obsproject.Studio
        - com.obsproject.Studio.OBSVkCapture
        - com.obsproject.Studio.Plugin.Gstreamer
        - com.obsproject.Studio.Plugin.GStreamerVaapi
        - org.libreoffice.LibreOffice
        - dev.alextren.Spot
        - com.github.IsmaelMartinez.teams_for_linux
      remove:
        - org.gnome.Cheese
        - org.gnome.eog

  - type: yafti
    custom-flatpaks:
    
  - type: script
    scripts:
      - alternatives-workarounds.sh
      - docker-compose.sh
      - pano.sh
      - image-info.sh
      - post-install.sh
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh